In [266]:
import pandas as pd

In [267]:
info = {
    "Name": ["Pawan", "Vishnu", "Ranjan"],
    "Marks": [90, 91, 92]
}

df = pd.DataFrame(info)

print(df)

     Name  Marks
0   Pawan     90
1  Vishnu     91
2  Ranjan     92

In [268]:
s = pd.Series([1, 2, 3, 4, 5,])
print(s)

#index
print(s[0])
print(s[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
1
4

In [269]:
s = pd.Series([13, 24, 34, 42], index=["Adam", "Eve", "Bob", "Charlie"])
print(s)
print(s["Adam"])
print(s["Bob"])

Adam       13
Eve        24
Bob        34
Charlie    42
dtype: int64
13
34

In [270]:
s1 = pd.Series([1, 2, 3, 4, 5,])
s2 = pd.Series([10, 20, 30, 40, 50,])

print(s1 + s2)
changed_s1 = s1.drop(0)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [271]:
#DATA FRAME

info = {
    "Name": ["Pawan", "Vishnu", "Ranjan"],
    "Marks": [90, 91, 92],
    "Age": [18, 19, 20]
}

df = pd.DataFrame(info)

print(df)
print(df.index)
print(df.columns)

     Name  Marks  Age
0   Pawan     90   18
1  Vishnu     91   19
2  Ranjan     92   20
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Age'], dtype='object')

In [272]:
df = pd.DataFrame([["Adam", 23], ["Bob", 23], ["Eve", 23]], columns=["name", "Age"])

print(df)

   name  Age
0  Adam   23
1   Bob   23
2   Eve   23

In [273]:
import numpy as np

np_arr = np.array([[1, 2, 3,], [4, 5, 6]])

df = pd.DataFrame(np_arr, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [274]:
#json data
df = pd.read_json("employee_data.json")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [275]:
#csv data
df = pd.read_csv("employee_data.csv")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [276]:
#Method
df = pd.read_csv("employee_data.csv")

# df.head() #print starting 5 rows
# df.tail(2)
# df.sample(3)

# df.info()

# df.shape

# df.describe()

# df.columns

df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [277]:
#AQI Data set

df = pd.read_csv("globalAirQuality.csv")

df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [278]:
#selecting data

df["country"]
df[["city", "aqi"]]

df.loc[0]
df.loc[0:2]  # start idx : end idx (included)

df.iloc[0]
df.iloc[0:2] # start idx : end idx (not included)

df.loc[0:2,["city", "aqi"]]

df.at[0, "city"]
df.iat[0, 2]

'New York'

In [279]:
#Filtering of data

df[df["aqi"] > 100]

df[ (df["aqi"] > 100) & (df["temperature"] > 30) ]

aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30) ] [["city", "aqi"]]

aqi_data.iloc[0]


#query
qui_val = 100
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]
df.query("aqi > @qui_val & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [280]:
#cleaning Data _ missing values

df = pd.read_csv("raw_data.csv")

df.isnull()  #=> df.isna()

df.isnull().sum()

df.dropna()#row drop
df.dropna(axis=1) #col drop

df.fillna(0)


cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [281]:
#handle Duplicates

# df.duplicated()
# df2 = df.copy()
# df2.drop_duplicates(inplace=True)

In [282]:
#Data Types

df.dtypes

df2 = df.copy()

# df2 = df2.fillna(0)
# df2["age"] = df2["age"].astype("int").copy()
# df2.dtypes

df["gender"].str.upper()
df["gender"].str.lower()
df["gender"].str.capitalize()

df["name"].str.split(" ")

df["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [283]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"])

aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [284]:
df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 60_000 else "10%")

gender_map = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"] =df2["gender"].map(gender_map)

df2 = df2.assign(new_income = df2["income"] * 1.1)

df2["country"] = df2["country"].replace("USA", "United States")

df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New-Income"]
df2.rename(columns={"Income":"Salary"})
df2.rename(index={1:"First"})

df2.sort_values("Income")
df2 = df2.fillna(50)
# df2.sort_values("Income", ascending=False)
sorted_df = df2.sort_values(["Income", "Age"])

sorted_df.sort_index()

#reset
sorted_df.reset_index()
sorted_df.reset_index(drop=True)

#Ranking
# sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="dense")
sorted_df[["Id", "Name", "Age", "Country", "Gender", "Income", "New-Income", "Tax"]]

    Id          Name   Age        Country Gender   Income  New-Income  Tax
4    4  Maria Garcia  34.0          Spain      F     50.0        50.0  10%
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0     49500.0  10%
3    3          Alex  50.0  United States      U  47000.0     51700.0  10%
5    5        Li Wei  27.0          China      M  51000.0     56100.0  10%
0    1      John Doe  29.0  United States      M  55000.0     60500.0  10%
1    1      John Doe  29.0  United States      M  55000.0     60500.0  10%
10  10   Emily Davis  31.0  United States     50  58000.0     63800.0  10%
8    8    Rachel Lee  29.0  United States      F  62000.0     68200.0  20%
2    2    Jane Smith  50.0         Canada      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0             50      M  68000.0     74800.0  20%
6    6            50  45.0          India      F  73000.0     80300.0  20%

In [285]:
df2 = df.copy()

new_col_order = [col for col in df2.columns if col != "id"] + ["id"]
df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [286]:
df2 = df.copy()

df2 = df2.drop_duplicates()
df2 =df2.fillna(0)

df2 = df2.sort_values("income")

df2 = df2.reset_index(drop=True)

df2.to_csv("sorted_data.csv")

In [296]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

df.groupby("gender")["income"].mean()
df.groupby("gender")["income"].max()

df.groupby("country")["income"].agg("mean", "min", "max")
df.groupby("country")["income"].aggregate("mean", "min", "max")

df.groupby("country")["income"].agg(avg_salary = "mean", min_salary = "min", max_salary = "max")

df.groupby("country").agg({
    "income" : "mean",
    "age" : "mean"
})

df.groupby("country").agg(
    max_salary = ("income", "max"),
    avg_age = ("age", "mean")
)

         max_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5

In [288]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0